Initial test data set for EBL
dcsaorg/DCSA-Information-Model pull request #19
Opened 2020-12-17 09:22 UTC by raisoman

2020-12-17 09:54 UTC, nt-as approved these changes

2020-12-17 13:14 UTC, nt-as approved these changes

2020-12-17 19:24 UTC, HenrikHL requested changes

2020-12-17 19:24 UTC, HenrikHL commented on datamodel/initdb.d/03_dcsa_im_v3_0.sql
> +    shipping_instruction_id uuid NULL,
This is wrong - please correct back again

2020-12-18 10:03 UTC, HenrikHL commented on datamodel/initdb.d/03_dcsa_im_v3_0.sql
> +    party_id uuid NULL,
```suggestion
    shipping_instruction_id uuid NOT NULL,
    party_id uuid NOT NULL,
```

2020-12-18 10:08 UTC, HenrikHL commented on datamodel/initdb.d/03_dcsa_im_v3_0.sql
>      shipment_id uuid NOT NULL,
```suggestion
    shipment_id uuid NULL,
```

2020-12-18 10:12 UTC, HenrikHL approved these changes

2020-12-18 10:16 UTC, HenrikHL approved these changes

2020-12-18 10:17 UTC, merged