Remove verified_gross_mass field
dcsaorg/DCSA-Information-Model pull request #25
Opened 2021-01-19 10:49 UTC by HenrikHL

If decided by MSC...

2021-01-19 10:56 UTC, nt-as reviewed
Requires changes to EBL to remove the usage of the field.

2021-01-19 15:23 UTC, nt-as requested changes
The field is referenced in 07 test data sql:

```

INSERT INTO dcsa_im_v3_0.shipment_equipment (
    id,
    shipment_id,
    equipment_reference,
    verified_gross_mass,
    cargo_gross_weight,
    cargo_gross_weight_unit
) VALUES (
    uuid('e0b81540-4066-11eb-9a35-7734806583a6'),
    uuid('561a5606-402e-11eb-b19a-0f3aa4962e0f'),
    'BMOU2149612',
    'Verified Gross Mass Dummy text::',
    4000,
    'KGM'
);
```

2021-01-19 20:05 UTC, HenrikHL commented
Good spotet - removed :-)

2021-01-22 09:34 UTC, nt-as approved these changes
LGTM

2021-01-26 12:29 UTC, HenrikHL commented
I am not sure this is valid any more. VGM should be removed completely (will know by the end of today...)

2021-01-26 12:32 UTC, nt-as commented
> 
> 
> I am not sure this is valid any more. VGM should be removed completely (will know by the end of today...)

Well, the title of the PR says "remove" !  :D

2021-01-27 09:10 UTC, HenrikHL commented on datamodel/testdata.d/07_test_data_ebl.sql
> +    'KGM'
```suggestion
```

2021-01-27 09:10 UTC, HenrikHL commented on datamodel/initdb.d/03_dcsa_im_v3_0.sql
> +	verified_gross_mass_unit varchar(3) NULL,
```suggestion
```

2021-01-27 09:10 UTC, HenrikHL commented on datamodel/initdb.d/03_dcsa_im_v3_0.sql
> -	verified_gross_mass varchar(250) NULL,
```suggestion
```

2021-01-27 09:11 UTC, HenrikHL commented on datamodel/initdb.d/03_dcsa_im_v3_0.sql
> +	verified_gross_mass_unit varchar(3) NULL,
```suggestion
```

2021-01-27 09:15 UTC, HenrikHL commented
It has been agreed that the VGM should be removed

2021-01-29 08:40 UTC, nt-as approved these changes

2021-01-29 13:04 UTC, merged