Create shipmentinformationtypecodes.csv
dcsaorg/DCSA-Information-Model pull request #82
Opened 2021-06-10 11:43 UTC by elulus

Adding
TRD
BOK
SHI
SRM
OOG
DGD
VGM
ARN

2021-06-11 06:40 UTC, nt-as requested changes
The file is not being loaded. We need a line a la https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/initdb.d/04_load_reference_data.sql#L18 for that csv file to be useful.

2021-06-11 12:02 UTC, HenrikHL commented on datamodel/referencedata.d/shipmentinformationtypecodes.csv
> +VGM,Verified Gross Mass
It was agreed in P1 that VGM is to be removed from ShipmentEvent

2021-06-11 12:03 UTC, HenrikHL commented on datamodel/referencedata.d/shipmentinformationtypecodes.csv
> +CAS,Cargo Survey
My guess is that CAS requires a link to an equipment (Container) - the structure for ShipmentEvents does not cater for this

2021-06-11 12:03 UTC, HenrikHL commented on datamodel/referencedata.d/shipmentinformationtypecodes.csv
> +VGM,Verified Gross Mass
...it was removed because it requires a link to an equipment (container number) which the ShipmentEvent does not cater for

2021-06-23 08:47 UTC, douradofrazer commented
Closing this as its consolidated in PR #96

2021-06-23 08:47 UTC, closed without merging